// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cipcnzgpupwrbdusowyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpcGNuemdwdXB3cmJkdXNvd3liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2ODk3OTcsImV4cCI6MjA4OTI2NTc5N30.v9tdvkxkfA-yFfEbhOUcXqtxq7x34MfRiLQ2LLBiG48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});